package eu.smartsocietyproject.pf.enummerations;

public enum State {
    INITIAL,
    PROVISIONING, COMPOSITION, NEGOTIATION, EXECUTION, CONTINUOUS_ORCHESTRATION,
    WAITING_FOR_PROVISIONING, WAITING_FOR_COMPOSITION, WAITING_FOR_NEGOTIATION, WAITING_FOR_EXECUTION, WAITING_FOR_CONTINUOUS_ORCHESTRATION,
    PROV_FAIL, COMP_FAIL, NEG_FAIL, EXEC_FAIL, ORCH_FAIL, WAITING_FOR_QUALITY_ASSURANCE, QUALITY_ASSURANCE, QUALITY_ASSURANCE_FAIL,
    FINAL, FAIL
}
